### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pbarry** [dropbox/PyHive#106]
Hi there! We noticed you haven't done a release since https://github.com/dropbox/PyHive/releases/tag/v0.2.1 almost a year ago. Will you be doing a new one soon? We'd love to use PyHive, but we need some of the recent changes like https://github.com/dropbox/PyHive/commit/498326c8373e61420fa6d773fafc4167a623feb3

**Comment by RohitTalwalkar** [comment]
Would love to see a new release!

**Comment by jingw** [comment]
yep, doing it as soon as I can merge & test the python 3 PR

**Comment by pbarry** [comment]
Thanks!!

**Comment by jingw** [comment]
I'm gonna try to figure out why CDH 5.11 is busted before doing a release

**Comment by jingw** [comment]
Done! v0.3.0 is on pypi

**Comment by pbarry** [comment]
Wow! so fast! Thanks!

**Comment by RohitTalwalkar** [comment]
Thanks, you guys rock!!
