### ISSUE TITLE
program hanging when I try to connect the hive. 

### ISSUE THREAD

**Issue by nanyoullm** [dropbox/PyHive#107]
I try to use pyhive.hive.Connection() with python2.7 to connect the hive. But the program is hanging.
my code is 

```
from pyhive import hive
con = hive.Connection(host='xxx.xxx.xxx.xxx', port=10000, configuration=None)   <-- hanging here, without error
```
or 
```
from pyhive import hive
con = hive.connect(host='xxx.xxx.xxx.xxx')   <-- hanging here, without error
```

By the way, I can use pyhive.presto to connect.
What should I do to handle it?

**Comment by jingw** [comment]
I think historically I've seen this happen when the connection is
incorrectly configured with a mismatching authentication mode. Check your
Hive site xml and the documentation on the connection constructor.
