### ISSUE TITLE
SQLAlchemy/Hive connect to Spark Thrift Server (based on HiveThriftServer2)

### ISSUE THREAD

**Issue by andreaslang** [dropbox/PyHive#108]
Hi, 

I was trying to connect to a Spark HiveThriftServer2 on Spark 2.1.0 and https://github.com/airbnb/superset with its SQLLab tool which is sqlalchemy based. While running queries with sqlalchemy works fine, superset uses among other things get_schema_names in sqlalchemy_hive.py. I realised that Spark returns a slightly different result for SHOW SCHEMAS. It uses databaseName instead of database_name as column name, the later being expected in sqlalchemy_hive.py.

I was able to make it work with a small modification which should work for Hive, too (see below) and I was wondering if there is a chance to bring that in?

```
def get_schema_names(self, connection, **kw):
        # Equivalent to SHOW DATABASES
        return [row[0] for row in connection.execute('SHOW SCHEMAS')]
```

There are a few other problems when superset tries to get table names (index of name different) and column definitions (with get_columns) for Spark temporary views, but that is because Spark does not seem to consistently work with schemas/dbs. For example 'SHOW TABLES IN myschema' would show the temporary view but 'DESCRIBE myschmea.myview' would produce an error. I haven't tested if it is the same for persisted tables. Anyway that is a spark bug.

I realise that you are probably not aiming to support the Spark Thrift server, but having this small change in would actually help me a lot and not break Hive compatibility. Should you be interested in implementing a sqlalchemy Spark dialect on the other hand, I'd be happy to get involved.

**Comment by jingw** [comment]
I'm open to patches that improve spark thrift compatibility without
increasing complexity. At the moment, I'm not interested in supporting
spark as a separate dialect, but iirc spark thrift aims to be compatible
with hs2. Thanks!

**Comment by andreaslang** [comment]
OK, I'll create the first pull request for the SHOW SCHEMAS part, which allows me at least to create the database in superset.

I will also create a Pull Request for the sqlalchemy Spark dialect which I will maintain in my fork to make a few more things work for me. It is just an extension for the Hive Dialect fixing the mentioned differences in behaviour and excluding temp tables from schemas.
