### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine(' status 80',))

### ISSUE THREAD

**Issue by basebase** [dropbox/PyHive#111]
python connection hive
I using sqlalchemy connection hive

> from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *
engine = create_engine('presto://localhost:10000/hive/default')
logs = Table('my_awesome_data', MetaData(bind=engine), autoload=True)
print select([func.count('*')], from_obj=logs).scalar()

get error message:

> requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x04\x00\x00\x00\x11Invalid status 80',))

**Comment by jingw** [comment]
It sounds like you're trying to use the Presto connector to connect to a Hive Thrift server (10000 is the default HS2 port). Assuming you're trying to connect to a HS2 server, you want to use hive://server:port/dtabase
