### ISSUE TITLE
TSaslTransportExcetion when connecting to HiveThriftServer2

### ISSUE THREAD

**Issue by wangxisea** [dropbox/PyHive#116]
I was following the example to connect to ThriftServer(attempting Superset on top of ES).
I got an error from the server saying:
ERROR TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TSaslTransportException: No data or no sasl data in the stream

Python error as follow:
NotImplementedError: Wrong number of arguments for overloaded function 'Client_setAttr'.
  Possible C/C++ prototypes are:
    setAttr(saslwrapper::Client *,std::string const &,std::string const &)
    setAttr(saslwrapper::Client *,std::string const &,uint32_t)

Any help is appreciated.

**Comment by jingw** [comment]
Try installing the dependencies: https://github.com/dropbox/PyHive/blob/master/setup.py#L43

The requirements were recently bumped.

**Comment by wangxisea** [comment]
The error was caused by C compiler on Windows, it works on Linux. Thanks!
