### ISSUE TITLE
No module named sasl

### ISSUE THREAD

**Issue by mosu027** [dropbox/PyHive#119]
when my code is `from pyhive import hive`  I  met the following question 
> No module named sasl
but when  I  "pip install sasl "
I met many questions , such as   " command 'x86_64-linux-gnu-gcc' failed with ",   " sasl/saslwrapper.cpp:8:22: fatal error: pyconfig.h' failed with  "...
Can you tell me how to fix it?
My operating system is centos.

**Comment by jingw** [comment]
Most likely you need to install some system package (apt/rpm/yum/whatever). Googling for the error message or missing *.h file should get you a pointer.

**Comment by mosu027** [comment]
OK, Thanks ! I have fixed it just now!

**Comment by abdulwahid24** [comment]
@mosu027 Please let us know what was the fix ?

**Comment by mosu027** [comment]
@abdulwahid24  just like  what jingw said , some system package (apt/rpm/yum/whatever)  should be installed. If you lack some package, let me Know , I try to help you!

**Comment by bkotesh** [comment]
**I am getting the below error:**
>>> import pyhs2
>>> conn = pyhs2.connect(host='172.16.0.XXX', port=10000, username='medwadmin',auth='NOSASL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/pyhs2/__init__.py", line 6, in connect
    from .connections import Connection
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/pyhs2/connections.py", line 6, in <module>
    import sasl
ImportError: No module named 'sasl'

2. But i had installed the package
ls -l  /usr/lib64 | grep libsasl
lrwxrwxrwx   1 root root       17 Sep 16 17:42 libsasl2.so -> libsasl2.so.3.0.0
lrwxrwxrwx   1 root root       17 Sep 16 17:42 libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x   1 root root   121328 Aug  3 00:44 libsasl2.so.3.0.0

**Comment by mosu027** [comment]
@bkotesh please pip list ,and  check if there is sasl. 
if not, please pip install sasl.
Then， if something is wrong, please tell me the details of error.

**Comment by bkotesh** [comment]
Python version: 3.5.4. Python and hive are in different servers.
can able to listen from the below server to that port.
>>> from pyhive import hive
>>> conn = hive.connect(host='172.16.0.XXX', port=10000, username='kotesh',auth='NOSASL')

Connection is taking more time. When disconnected below error is thrown.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/pyhive/hive.py", line 64, in connect
    return Connection(*args, **kwargs)
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/pyhive/hive.py", line 164, in __init__
    response = self._client.OpenSession(open_session_req)
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 187, in OpenSession
    return self.recv_OpenSession()
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 199, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 161, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/home/medwadmin/anaconda3/lib/python3.5/site-packages/thrift/transport/TSocket.py", line 117, in read
    buff = self.handle.recv(sz)
KeyboardInterrupt
`
Thanks in advance

**Comment by mosu027** [comment]
@bkotesh I'm afraid that i have to say sorry to you! It's a  long time since I fixed this question.The trouble you have met I have no idea how to solve it.Very sorry!

**Comment by niharikasharma** [comment]
Hi @mosu027 , I tried installing sasl using 'pip install sasl' command, but got the following error. Could you please help with the following error? Thank you for the time.  
appdata\local\temp\pip-install-8gee3a8r\sasl\sasl\saslwrapper.h(22): fatal error C1083: Cannot open include file: 'sasl/sasl.h': No such file or directory

**Comment by achyuthan1991** [comment]
Hi niharikasharma, this is a late response, but take a look at this link: http://dwgeek.com/guide-connecting-hiveserver2-using-python-pyhive.html/. It provides instructions for installing pyhive and discusses why sasl might not work. I am not sure if that is the exact issue that you are getting though. He explains an sasl related error just before step 2 on the link.

**Comment by ouday-coder** [comment]
def hiveconnection(host_name, port, user, database):
    conn = hive.Connection(host=host_name, port=port, username=user,
                           database=database, auth='NOSASL')
