### ISSUE TITLE
Extra requirements are not installed on Python 3.6

### ISSUE THREAD

**Issue by Hardtack** [dropbox/PyHive#120]
I'm trying to install pyhive with hive interfaces with pip.
But pip does not install extra requirements for hive interface.

Here's my shell output with warning messages

```
(venv) $ python --version
Python 3.6.1
(venv) $ pip --version
pip 9.0.1 from /Users/owen/.virtualenvs/venv/lib/python3.6/site-packages (python 3.6)
(venv) $ pip install pyhive[hive]
Requirement already satisfied: pyhive[hive] in /Users/owen/.virtualenvs/venv/lib/python3.6/site-packages
  Ignoring sasl: markers 'extra == "Hive"' don't match your environment
  Ignoring thrift-sasl: markers 'extra == "Hive"' don't match your environment
  Ignoring thrift: markers 'extra == "Hive"' don't match your environment
Requirement already satisfied: future in /Users/owen/.virtualenvs/venv/lib/python3.6/site-packages (from pyhive[hive])
```
I'm working on macOS 10.12.4 and Python 3.6.1 installed by pyenv.

`sasl`, `thrift-sasl`, `thrift` are installed very well when I try to install them manually (`pip install sasl ...`)

It works very well when I try to install in Python 2.7.11 installed by pyenv.

**Comment by Hardtack** [comment]
As I think, It happens because of thrift_sasl which does not support python 3.6 yet.

`Programming Language :: Python :: 3.6` does not exist in categories (https://pypi.python.org/pypi/thrift_sasl/0.2.1)

Is it right?

**Comment by jingw** [comment]
That sounds correct. The CI environment is installing from master:
https://github.com/dropbox/PyHive/blob/master/dev_requirements.txt
