### ISSUE TITLE
ABANDONED_QUERY (2) while using the presto.py module

### ISSUE THREAD

**Issue by srchilukoori** [dropbox/PyHive#123]
Hi,

When I'm running a CREATE Table query using the presto.py module, my query is terminated with a code of 'ABANDONED_QUERY (2)'. Could you please help me how to fix this error. Thank you.

**Comment by jingw** [comment]
I think you need to exhaust the result set of the query. The error you got means Presto didn't hear back from you after submitting the query.

(it's probably a bug that fetchall needs to be called even on non-result-returning queries)

**Comment by srchilukoori** [comment]
It works when I called fetchall().  Thank you.
