### ISSUE TITLE
presto decimal show UNKNOWN

### ISSUE THREAD

**Issue by 561152** [dropbox/PyHive#124]
presto decimal type show UNKNOWN
![image](https://cloud.githubusercontent.com/assets/28682782/26393173/97d51d4c-409b-11e7-883e-6c0f65a9ef34.png)

**Comment by jingw** [comment]
I'm not sure what software that is, but PyHive returns the decimal type from Presto as decimal:
https://github.com/dropbox/PyHive/blob/master/pyhive/tests/test_presto.py#L68
