### ISSUE TITLE
requests is missing as dependency

### ISSUE THREAD

**Issue by amstree** [dropbox/PyHive#126]
I created a new virtual environment and installed pyhive, using python2.7, and got following error:

In [1]: from pyhive import presto
ImportError                               Traceback (most recent call last)
<ipython-input-1-6ab4a070b662> in <module>()
----> 1 from pyhive import presto

/.virtualenvs/test/lib/python2.7/site-packages/pyhive/presto.py in <module>()
     16 import getpass
     17 import logging
---> 18 import requests
     19 
     20 try:  # Python 3

ImportError: No module named requests

**Comment by jingw** [comment]
This is intentional. Requests is an optional dependency. See the README for install instructions.
