### ISSUE TITLE
Unicode query breaking 

### ISSUE THREAD

**Issue by Chuseuiti** [dropbox/PyHive#127]
Im trying to do a simple unicode query and it breaks with the following statement:

> `>>> d.execute("select *  from table_name where Column1="+u'\u6c34\u91ce\u7dda')`

Error:

`pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(errorCode=40000, errorMessage=u"Error while compiling statement: FAILED: ParseException line 1:51 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in expression specification", sqlState=u'42000', infoMessages=[u"*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 1:51 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in expression specification:17:16", u'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:388', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:193', u'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:276', u'org.apache.hive.service.cli.operation.Operation:run:Operation.java:324', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:499', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:475', u'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:270', u'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:507', u'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', u'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', u'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', u'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', u'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', u'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', u'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', u'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', u'java.lang.Thread:run:Thread.java:748', u"*org.apache.hadoop.hive.ql.parse.ParseException:line 1:51 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' in expression specification:21:5", u'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:207', u'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:166', u'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:444', u'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1242', u'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1229', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:191'], statusCode=3), operationHandle=None)`

**Comment by jingw** [comment]
You're missing quotes. Your string evaluates to
```
>>> print "select * from table_name where Column1="+u'\u6c34\u91ce\u7dda'
select * from table_name where Column1=水野線
```

**Comment by Chuseuiti** [comment]
If I try to query, it fails even thought is able to print it . The message is cannot recognition service input.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jingw** [comment]
You're passing invalid SQL to Hive. There needs to be quotes inside your python string around the SQL string.
```
select * from table where column='sddsfdsf'
```

**Comment by Chuseuiti** [comment]
Aaaa.. awesome ! 
I just forgot to  write the extra "" on the code for the string
