### ISSUE TITLE
[Question] pyhive.hive.Connection, SASL and python 3.5 - "Could not start SASL"

### ISSUE THREAD

**Issue by ThomasBury** [dropbox/PyHive#131]
HI,

I'm a Hadoop newbie, so don't shoot me yet. I want to set a hive connection using the hive.Connection with python 3.5.2 but the SASL package seems to cause a problem. I saw on a forum that SASL is compatible only with 2.7 python. Is that right ? 

Thank you in advance !
Tom

from pyhive import hive
#conn = hive.Connection(host="aa10larv0004", port=10000)
conn = hive.Connection(host="aa10larv0004")
import pandas as pd
 
 
---------------------------------------------------------------------------
TTransportException                       Traceback (most recent call last)
<ipython-input-12-f070266cbd59> in <module>()
      1 from pyhive import hive
      2 #conn = hive.Connection(host="aa10larv0004", port=10000)
----> 3 conn = hive.Connection(host="aa10larv0004")
      4 import pandas as pd
 
/opt/anaconda3/lib/python3.5/site-packages/pyhive/hive.py in __init__(self, host, port, username, database, auth, configuration)
    102
    103         try:
--> 104             self._transport.open()
    105             open_session_req = ttypes.TOpenSessionReq(
    106                 client_protocol=protocol_version,
 
/opt/anaconda3/lib/python3.5/site-packages/thrift_sasl/__init__.py in open(self)
     70     if not ret:
     71       raise TTransportException(type=TTransportException.NOT_OPEN,
**---> 72         message=("Could not start SASL: %s" % self.sasl.getError()))**
     73
     74     # Send initial response
 
TTransportException: TTransportException(message="Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found'", type=1)

**Comment by ThomasBury** [comment]
We (I should say, IT-team) find a solution

Upgrade of python packages thrift (to version 0.10.0) and PyHive (to version 0.3.0) don’t know why the version we used wasn’t the latest.

Added the following:

```
<property>
<name>hive.server2.authentication</name>
<value>NOSASL</value>
</property>
```
To the following Hive config parameters in Cloudera Manager:

HiveServer2 Advanced Configuration Snippet (Safety Valve) for hive-site.xml Hive Client Advanced Configuration Snippet (Safety Valve) for hive-site.xml necessary so that HUE would work

```
from pyhive import hive
conn = hive.Connection(host="myserver", auth='NOSASL')
import pandas as pd
import sys

df = pd.read_sql("SELECT * FROM my_table", conn) 
print(sys.getsizeof(df))
df.head()
```
worked without problem/error.

Best, Tom

**Comment by y2k-shubham** [comment]
@ThomasBury 
- My thrift package is already at 0.10.0 and PyHive even higher at 0.5.0
- I already have the NOSASL authentication property in hive-site.xml
- adding `auth='NOSASL'` parameter to the connection instantiation statement changes the error from `Could not start SASL` to `AttributeError: TBinaryProtocol instance has no attribute '_fast_encode'`

**Comment by ThomasBury** [comment]
@y2k-shubham 
Strange, since NOSASL is specified, the authentification process is "skipped". I don't know much more about it. It could be a mismatch between versions
I found this  [some related issue](https://issues-test.apache.org/jira/browse/THRIFT-4089)

Sorry I don't have a straightforward answer.

**Comment by dhananjaymehta** [comment]
@ThomasBury I had similar problem, I had set authentication none and had all the packages required (sasl, thrift, pyhive). I was missing a plain kerberos plugin, which was being used for authentication and had to do the following - 
`yum install cyrus-sasl-plain`
You can read more here - http://grokbase.com/t/hive/user/144tajctxv/error-in-sasl-client-start-4-sasl-4-no-mechanism-available-no-worthy-mechs-found

**Comment by freshforlife** [comment]
The hack by @dhananjaymehta , worked for me too.
