### ISSUE TITLE
how pyhive to return yarn application job id

### ISSUE THREAD

**Issue by darkz1984** [dropbox/PyHive#134]
As the title mentioned.
I want to get the information of hive job I submit to pyhive driver ,then I can get some information about the hive job .

**Comment by jingw** [comment]
Hive doesn't have an API for this, but it's printed out in `fetch_logs` if you're willing to regex scan stuff. Technically a single Hive query can map to zero, one, or multiple YARN jobs depending on the query.

**Comment by wispedia** [comment]
when i use cursor.fetch_logs(), it has returned a empty list
