### ISSUE TITLE
Array/Map data type support?

### ISSUE THREAD

**Issue by achiku** [dropbox/PyHive#14]
First of all, thank you for open sourcing such an awesome library! I'm just curious, but do you have any plan to integrate Array/Map datatype into PyHive?

**Comment by jingw** [comment]
I don't have an immediate plan to change the output format for list/map if
that's what you mean. As I remember, presto switched to returning
maps/arrays as JSON instead of string dumps a while ago. Are you referring
to hive?

(Changing the output format would be backwards incompatible, so I'd need to
be careful with it at dropbox)

On Thursday, February 12, 2015, Akira Chiku <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> First of all, thank you for open sourcing such an awesome library! I'm
> just curious, but do you have any plan to integrate Array/Map datatype into
> PyHive?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dropbox/PyHive/issues/14>.
>


-- 
Sent from phone

**Comment by achiku** [comment]
Sorry for being unclear on the question and really late to reply. And yes, you are right. I was talking about Presto and now it returns JSON and PyHive can read and properly translate it to Python list! I use postgresql dialect to define a mapping, but ```Item = Table('item', MetaData(bind=engine), autoload=True)``` works fine too although it sends warning message like ``` SAWarning: Did not recognize type 'array<bigint>' of column 'tag'```.

Create Hive external table

```
DROP TABLE item;
CREATE EXTERNAL TABLE item (
    id INT
    ,name STRING
    ,category STRING
    ,price BIGINT
    ,cost BIGINT
    ,tag ARRAY<INT>
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
LOCATION '/mnt/var/hive/item/';
```

Create test data

```python
import random


def hive_array_format(l):
    return "\002".join(l)


if __name__ == '__main__':
    for i in xrange(100):
        tags = hive_array_format([str(x) for x in xrange(random.randint(5, 15))])
        category_id = random.randint(1, 3)
        price = random.randint(100, 10000)
        cost = random.randint(100, 1000)
        print "{id},item{id},category{category_id},{price},{cost},{tags}".format(
            id=i, price=price, cost=cost, category_id=category_id, tags=tags
        )
```

Copy test data to HDFS

```
 hdfs dfs -copyFromLocal ./item.txt  /mnt/var/hive/item/
```

Select data from Presto using PyHive

```python
from sqlalchemy import BigInteger, Column, MetaData, String, Table
from sqlalchemy.engine import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.dialects.postgresql import ARRAY

metadata = MetaData()

Item = Table(
    'item', metadata,
    Column('id', BigInteger),
    Column('name', String),
    Column('category', String),
    Column('price', BigInteger),
    Column('cost', BigInteger),
    Column('tag', ARRAY(BigInteger)),
)

engine = create_engine('presto://localhost:8080/hive/default')
Session = sessionmaker(bind=engine)
session = Session()

if __name__ == '__main__':
    items = session.query(
        Item.c.name,
        Item.c.tag
    ).limit(10)

    for i in items:
        print i.name, i.tag, type(i.tag)
```

Output

```
item0 [0, 1, 2, 3, 4, 5, 6, 7] <type 'list'>
item1 [0, 1, 2, 3, 4] <type 'list'>
item2 [0, 1, 2, 3, 4, 5, 6, 7] <type 'list'>
item3 [0, 1, 2, 3, 4, 5, 6, 7] <type 'list'>
item4 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>
item5 [0, 1, 2, 3, 4, 5, 6, 7, 8] <type 'list'>
item6 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <type 'list'>
item7 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] <type 'list'>
item8 [0, 1, 2, 3, 4, 5, 6, 7] <type 'list'>
item9 [0, 1, 2, 3, 4, 5, 6, 7] <type 'list'>
```

**Comment by achiku** [comment]
@jingw Can I close this issue since it's apparently not an issue?

**Comment by jingw** [comment]
Happy to have issues deemed non-issues :)

**Comment by achiku** [comment]
@jingw Thanks!
