### ISSUE TITLE
`async` keyword in Python 3.7

### ISSUE THREAD

**Issue by matthewwardrop** [dropbox/PyHive#148]
Hi!

In Python 3.7, `async` becomes a keyword, and so will not be able to be used as a variable name. Currently, async is used [here](https://github.com/dropbox/PyHive/blob/90b587b2d04abc806676f40e32d3f50285db9e84/pyhive/hive.py#L275). What do you think is a good name to use to replace this variable?

`async_`?
`wait` (the boolean inverse)?

**Comment by jingw** [comment]
SQLAlchemy handles this stuff by appending underscore, e.g. `and_`, so I propose we do the same thing. How's backwards compatibility supposed to work if it's a keyword now? Presumably we can't declare both or do if/else logic, since we'd get a syntax error. I guess it's possible to import a separate shim file depending on whether async is a keyword, but that seems ugly.

Amusingly the PEP claims "100% backwards compatibility" https://www.python.org/dev/peps/pep-0492/#backwards-compatibility

**Comment by matthewwardrop** [comment]
The original proposal *was* backward compatible (`async` was treated as a keyword in only a few contexts); but with Python 3.7 `async` is being promoted to fully-fledged feature of the platform. As noted in that PEP documentation:

```
async and await names will be softly deprecated in CPython 3.5 and 3.6. In 3.7 we will transform them to proper keywords. Making async and await proper keywords before 3.7 might make it harder for people to port their code to Python 3.
```

Unfortunately, this is going to break several modules though, including `pyhive` and `omniduct`.

I'm torn in the case of `omniduct` as to whether I want to the relevant variables with `async_`, or change to `sync` or `wait` and invert the logic. Sincec I usually encourage users to pass in these values as keyword arguments, appending the underscore is a bit tacky in my use case.

**Comment by jingw** [comment]
I think backwards compatibility can work by defining a new async_/asynchronous/wait/whatever param to handle positional callers and taking **kwargs to handle named callers. (We'd also validate that kwargs only every contains `async`.)

We have a bit over a year to deal with this, so I think I'll punt on taking action here in case Python decides to backtrack on the extra keyword.

**Comment by kevinsimard** [comment]
I am actually facing this issue right now with Python 3.7 and Hive2Server library. The keyword is causing my python script to fail cause of bad syntax. Any plan on fixing this soon?

**Comment by kevinsimard** [comment]
@matthewwardrop

**Comment by matthewwardrop** [comment]
@kevinsimard I'm not the developer of this package; you'll have to reach out to @jingw .

**Comment by naoyak** [comment]
@gsilk is there a way to prioritize this issue?

**Comment by gsilk** [comment]
Thanks guys, and apologies for the delayed response on this. I'll include this in the next release.

**Comment by naoyak** [comment]
Thanks @gsilk! Would be great if you could tag a release soon as well :)

**Comment by gsilk** [comment]
New release is out: https://pypi.org/project/PyHive/0.6.1/

Let me know if there are any problems! Thanks

**Comment by nicolasesnis** [comment]
Hi,
I'm using release 0.6.2 and I can't seem to use the `_async` keyword in cursor.execute()

`cursor.execute("""SELECT * FROM impressions LIMIT 10""", async_=True)`

will return a TypeError

`TypeError: execute() got an unexpected keyword argument 'async_'`

**Comment by kobayashley** [comment]
Hello @nicolasesnis, Have you solved this error? I am running into the exact same error on release 0.6.3. 
```
cursor.execute(query_str, async_=True)

execute() got an unexpected keyword argument 'async_'  SyntaxError: invalid syntax
```
