### ISSUE TITLE
Should not have nextUri if failed with PrestoDB 0.181

### ISSUE THREAD

**Issue by damiencarol** [dropbox/PyHive#149]
We have this error with Superset
```
Should not have nextUri
```

**Comment by jingw** [comment]
Could you include repro instructions, or better yet, a regression test and bugfix?

**Comment by damiencarol** [comment]
Working on it.

**Comment by dmigo** [comment]
Any progress on this one? I have the same issue, but not quite sure about the reason behind it yet.

**Comment by damiencarol** [comment]
@dmigo I can't reproduce it :/ and we changed our Superset version. So I don't have prod env to analyse it again.
I'm sorry but I can't fix or give anymore help :(
