### ISSUE TITLE
why _fetch_while needs to sleep

### ISSUE THREAD

**Issue by kevinGuazi** [dropbox/PyHive#153]
hi: 
`
    def _fetch_while(self, fn):
        while fn():
            self._fetch_more()
            #if fn():
            #    time.sleep(self._poll_interval)
`
in  common.py , class DBAPICursor

why sleep here

**Comment by jingw** [comment]
It sleeps if there's no data, i.e. we're blocked on the execution of the backend job. If there is data, it doesn't sleep.
