### ISSUE TITLE
How to get the hive server error msg?

### ISSUE THREAD

**Issue by petersunbag** [dropbox/PyHive#160]
I have a bad sql like

`select * from log where concat_ws('-',year,month,day) between 2017-09-13 and 2017-09-19`
which should has _2017-09-13_ and _2017-09-19_ surrounded  by ''.

In beeline, it will result the error msg like

> Error: Error while compiling statement: FAILED: ParseException line 2:0 missing EOF at 'select' near ']' (state=42000,code=40000)

but in PyHive, it goes normal with the empty result []. By the way, I am using it through sqlalchemy.
I've tried to use _echo=True_ in the _create_engine()_ function and _logging_ by
`import logging`
`logging.basicConfig()`
`logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)`
but both can not output the error msg.
> 2017-09-20 12:17:22,904 INFO sqlalchemy.engine.base.Engine select * from log where concat_ws('-',year,month,day) between 2017-09-13 and 2017-09-19
> INFO:sqlalchemy.engine.base.Engine:select * from log where concat_ws('-',year,month,day) between 2017-09-13 and 2017-09-19
> 2017-09-20 12:17:22,905 INFO sqlalchemy.engine.base.Engine {}
> INFO:sqlalchemy.engine.base.Engine:{}

So I wonder if there is a way to get the server side error, it will be convenient to debug.

**Comment by jingw** [comment]
Are you sure you're putting the same SQL query through beeline and PyHive? The query you posted looks syntactically valid and does not contain the character `]` mentioned in your beeline log.

`2017-09-13` is valid Hive syntax. It just means integer subtraction.

We do propagate exceptions on invalid queries, e.g. https://travis-ci.org/dropbox/PyHive/jobs/278465004

**Comment by petersunbag** [comment]
> 2017-09-13 is valid Hive syntax. It just means integer subtraction.

That's the point, thanks!
