### ISSUE TITLE
PyHive fetchmany get stuck for sometime

### ISSUE THREAD

**Issue by changzong** [dropbox/PyHive#166]
Hi there,

We just encountered a very strange problem when using PyHive.

We use PyHive cursor to execute a Hive query and then fetch a fix number of rows from the result. This basic process is like:

```
...
cursor.execute(sql)
rows = cursor.fetchmany(num)
...
```

However, for the same query, there is a probability to get stuck at cursor.fetchmany(num) method (sometimes passed, sometimes stuck). We changed the num for some numbers and it still get stuck sometimes. 

Anyone can share some experience about this problem?

Thanks

Channing

**Comment by jingw** [comment]
I doubt this is something we can help you with on the client side. The fetch methods end up calling into HS2's Thrift API, and most likely, that Hive server is the source of the slowness / hanging.

If you can get some trace logs and/or stacktraces, that will confirm if PyHive is just waiting on Hive or is doing something in its own code. Check out the "py-bt" command in https://docs.python.org/devguide/gdb.html, and try dumping a bunch of prints in hive.py to see what's going on.
