### ISSUE TITLE
Couldn't execute join queries using Sqlalchemy ORM?

### ISSUE THREAD

**Issue by gowtham-sai** [dropbox/PyHive#169]
I defined models using Sqlalchemy and using graphene. 

I have two tables like users and orders. 
The query is something similar like the below.,

select a.id, b.email from db.users a inner join db.users b on a.id = b.id

When using presto (MySQL connector. Actually use case is different), as engine, for each user is the query is executing. 

When used MySQL engine, for all users it executed in single db Query. 

What I'm missing here? How do I make it execute in this single db call?

**Comment by jingw** [comment]
I don't understand your question. What do you mean by "for each user is the query is executing"?
It sounds like this is question better suited for https://github.com/prestodb/presto though. This client just takes your query and sends it off to Presto, which is responsible for figuring out how to execute it.

**Comment by Gowtham95india** [comment]
This is definitely not related to presto db. If I'm not wrong, this about the implementation pyhive/presto. 

Let's say we have 10 users in users table.  In case of presto sqlalchemy, ( I added little print statement at presto#exexcute  ) it will call execute 10 times, once for each user.  

The query will be like 
select .... Blah blah.. where id = 1 limit 1;

select .... Blah blah.. where id = 2 limit 2;


Where as in case of MySQL sqlalchemy, the query is like

select ...... where id in (1,2,3,4,...10);

So, it's definitely implementation difference between both.

**Comment by jingw** [comment]
I don't know. It would be helpful to have a concrete example in the form of a test added to test_sqlalchemy_presto.py.

The SQL generation is handled by SQLAlchemy. I don't directly control how SQLAlchemy calls presto.Cursor.execute. Maybe there's some dialect option that needs to be fiddled with.

**Comment by gowtham-sai** [comment]
Closing this issue. GraphQL Python has no implementation.

**Comment by gowtham-sai** [comment]
Closing this issue. GraphQL Python has no implementation.
