### ISSUE TITLE
Error Passing Session Configuration for presto using SQLAlchemy

### ISSUE THREAD

**Issue by Dineshkarthik** [dropbox/PyHive#175]
When passing session configuration using `connect_args` in SQLAlchemy as documented in README,

`create_engine('presto://user@host:443/hive', connect_args={'query_max_run_time': '1234m'})`

it throws the following error:
`StatementError: (builtins.TypeError) __init__() got an unexpected keyword argument 'query_max_run_time' [SQL: 'select * from my_table limit 10']`

This can be fixed by passing the connect_args as follows:
`create_engine('presto://user@host:443/hive', connect_args={'session_props':{'query_max_run_time': '1234m'}})`

Created a pull request updating this.

**Comment by KevinFarrell** [comment]
Fixed by #176
