### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by matthewwardrop** [dropbox/PyHive#190]
@jingw @KevinFarrell There's been some useful commits lately, and especially of interest to me is #164 (which stops pyhive from freaking out in err and hiding useful debugging information from users). Would it be possible to make a new release soon?

I'm not sure what your policy is on this, but as the primary developer of omniduct (https://github.com/airbnb/omniduct), I have vested interest in making sure everything works well on the pyhive side. If you need another maintainer, you will find me willing :).

**Comment by jingw** [comment]
Hello! Sorry about the delay here. I can get a release out tomorrow.

I'll email you separately about maintenance at your committer email.

**Comment by jingw** [comment]
done!

**Comment by matthewwardrop** [comment]
Thanks @jingw !
