### ISSUE TITLE
can't execute multiple statements separated by ';'

### ISSUE THREAD

**Issue by zpz** [dropbox/PyHive#195]
[This issue is not quite specific to PyHive alone, but I couldn't get help elsewhere, and PyHive seems to be more active... sorry]

I'm using impyla but pyhive appears to have similar difficulties with this:

How can I execute arbitrary multi-statement Hive scripts, which work fine in Hive interpreter, through pyhive or impyla?

Both expects a single Hive QL statement only (';' in the middle fails to parse). For 'regular' write statements I can split them and run one at a time. For

set hive.xxx=yyy

type of statements the configuration argument to Cursor appears to work. But I have one script that contains a

ADD JAR ...

and I haven't figured out how to make it work. Another case is

USE database_name; ...

I can execute this statement by itself, but its effect does not appear to be picked up by the subsequent statement.

My question is, if I have an arbitrary multi-statement Hive script that is happily accepted by the Hive interpreter, is there a way to run the same sequence through pyhive or impyla?

Thanks.

**Comment by zpz** [comment]
Issues with 'ADD JAR' solved; it's my bug. Other 'multiple statements' can be worked around.

**Comment by wingr** [comment]
@zpz I am also struggling with the `ADD JAR` command not being picked up by subsequent statements. I am curious to hear how you got this working.

Thanks!

**Comment by zpz** [comment]
I gave up on doing 'ADD JAR' in some 'meta' way in the connection. Instead,
I included this statement in the Hive script and executed the statement
sequence. I struggled for days because this did not work due to a stupid
bug.

Zepu

**Comment by wingr** [comment]
Thanks for the quick response @zpz! From the searching I did yesterday, it looks like there is a bigger issue with JAR files and thin clients in general and the preferred way is to load the JARs where Hive can find them on the server side using the `hive-site.xml` file and an entry like:

```xml
<property>
    <name>hive.aux.jars.path</name>
    <value>some_path_to_jar</value>
</property>
```

That said, please correct me if this is incorrect and there is a way to load JARs using PyHive directly. I would love to be able to run queries requiring JARs without interacting with and restarting the Hive server itself.
