### ISSUE TITLE
Can not find udf function

### ISSUE THREAD

**Issue by badbye** [dropbox/PyHive#209]
I already did the configuration to add the jar file to the classpath.
The function works when I use the hive/beeline command. However, it becomes invalid when I switch to this PyHive package.
What should I do to fix it?

**Comment by badbye** [comment]
Since the sql is running via hiveserver2, pyhive is just a connector. so I guess I can do nothing with the python api?

**Comment by badbye** [comment]
Confirmed, it is not Pyhive's fault.

**Comment by victor9496** [comment]
Hi, I wonder if you solve the problem implementing udf in pyhive, thank you!
