### ISSUE TITLE
Pre-fetch method

### ISSUE THREAD

**Issue by Downchuck** [dropbox/PyHive#21]
When working with large amounts of data, it'd be nice to have fetch continue to pull records in another thread. For example,  cursor.prefetchmany(100000) would return 100k rows on the first call, then spawn a new thread to fetch the next 100k rows.

**Comment by Downchuck** [comment]
Basically, this:
```
        class Prefetch:
                def __init__(self, cursor, size = 10000):
                        self.cursor = cursor
                        self.currentOne = []
                        self.currentTwo = []
                        self.currentThread = None
                        self.size = size

                def records(self):
                        self.currentTwo = self.cursor.fetchmany(self.size)

                def fetch(self):
                        thread = threading.Thread(target=self.records)
                        thread.daemon = True
                        thread.start()
                        return thread
                def has(self):
                        if len(self.currentOne) == 0:
                                if len(self.currentTwo) == 0:
                                        self.fetch().join()
                                        if len(self.currentTwo) == 0:
                                                return False
                                self.currentOne = self.currentTwo
                                self.currentTwo = []
                        if len(self.currentTwo) == 0:
                                if self.currentThread == None:
                                        self.currentThread = self.fetch()
                        return True
                def pop(self):
                        return self.currentOne.pop()
```

**Comment by jingw** [comment]
Thanks for the suggestion, but I think this is best left to the users of this library. I'd like to keep this library scoped as a minimalistic DB-API connector.

Regarding your use case:
If the bottleneck is fetching rows, then adding this background fetch won't help. On the other hand, if the bottleneck is processing rows, then it would probably help more to decouple fetching from consumption by having a bunch of worker threads / subprocesses. Also, depending on what you're doing, you may be better served via custom MRs  / Hive transform scripts. At Dropbox we generally only use Python for lower volume processing where all the real work happens in Hive/Presto.

**Comment by Downchuck** [comment]
Understood. For anyone else coming across, an iterator is also handy, when paired with pre-fetching chunks.

http://code.activestate.com/recipes/137270-use-generators-for-fetching-large-db-record-sets/
