### ISSUE TITLE
enable setting ApplicationName property on Connection instance

### ISSUE THREAD

**Issue by bhargavi-damodaran** [dropbox/PyHive#231]
One of the ways to set a sourcename in presto is to set the ApplicationName client info property on the Connection instance (https://prestodb.io/docs/current/admin/resource-groups.html) . We're using pyhive to connect to presto and pyhive does not support setting the ApplicationName property. This feature would be helpful to create a resourceGroup by sourceName and manage resources on presto more efficiently.

**Comment by bhargavi-damodaran** [comment]
I just realized that all interaction to presto happens through cursor which has the ability to set source - https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L92.. Thanks

**Comment by cnuss** [comment]
Seems like this functionality already exists: https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L180

We should set `source` when creating your Cursor/Connection
