### ISSUE TITLE
SyntaxError in Python 3.7 when importing hive

### ISSUE THREAD

**Issue by ragerin** [dropbox/PyHive#235]
Importing hive yields the following error, with Python 3.7:

```python
>>> from pyhive import hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\pyhive\hive.py", line 337
    def execute(self, operation, parameters=None, async=False):
                                                      ^
SyntaxError: invalid syntax
```

Undoubtedly due to `async` being a keyword in 3.7.

**Comment by ragerin** [comment]
Sorry, I see that this was just fixed. Just not pushed to pip.

**Comment by gsilk** [comment]
New release is out: https://pypi.org/project/PyHive/0.6.1/

Let me know if there are any problems! Thanks
