### ISSUE TITLE
SET stament

### ISSUE THREAD

**Issue by mporracindie** [dropbox/PyHive#264]
Hi, im getting errors that i cant run SET staments on runtime

> SET hive.exec.dynamic.partition.mode=nonstrict

Is this supported? How can i fix this?

**Comment by mporracindie** [comment]
Full error:

> 08:49:49 Error ejecutando Hive: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: Cannot modify SET hive.exec.dynamic.partition.mode at runtime. It is not in list of params that are allowed to be modified at runtime:27:26', 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.HiveCommandOperation:runInternal:HiveCommandOperation.java:118', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'sun.reflect.GeneratedMethodAccessor169:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:498', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:422', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1844', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy35:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:748'], sqlState='42000', errorCode=1, errorMessage='Error while processing statement: Cannot modify SET hive.exec.dynamic.partition.mode at runtime. It is not in list of params that are allowed to be modified at runtime'), operationHandle=None)

**Comment by mythrocks** [comment]
This doesn't look like it's on the PyHive side. You want to check the HiveServer2 instance, to see what confs have been blacklisted/whitelisted, specifically, the setting for `hive.security.authorization.sqlstd.confwhitelist`. I suspect `hive.exec.dynamic.partition.mode` isn't listed there.

**Comment by mporracindie** [comment]
I fixed it adding it on the connection:

> hiveConnection = hive.Connection(
>             host=HIVE_HOST,
>             port=HIVE_PORT, 
>             username=HIVE_USER,
>             database="default",
>             password=HIVE_PASS,
>             auth="LDAP",
>             configuration={"hive.exec.dynamic.partition.mode":"nonstrict"}
> )

And it fixed the problem.
