### ISSUE TITLE
How to get mapreduce job id from a hive query?

### ISSUE THREAD

**Issue by keeyonghan** [dropbox/PyHive#28]
I am wondering if it is possible to get back mapreduce job id from a hive query in PyHive? 

Thanks!

**Comment by jingw** [comment]
Sorry, I don't believe Hive thrift exposes the MR job id. As far as I know, the only solution is to search the JobTracker UI.

**Comment by ptallada** [comment]
If you need the job ID to track the progress of the query, thrift exposes a method to retrieve query logs and you can see the progress there. Beeline client uses this API too to report progress

Is this method implemented in pyhive? I am very much interested in this :)

Thanks!

**Comment by jingw** [comment]
Sorry, this has not been implemented.
