### ISSUE TITLE
Pick up "supports_sane_rowcount"

### ISSUE THREAD

**Issue by shawnzhu** [dropbox/PyHive#315]
It doesn't fully support Update/Delete statement against Hive 3:

https://github.com/dropbox/PyHive/blob/9265b580963edd7303d4f21bf06af05dc3f8488b/pyhive/common.py#L62-L65

Some downstream apps like Alembic are sensitive about `resultset.rowcount`:

https://github.com/sqlalchemy/alembic/blob/4ff7c6927477c37e2a2ba89b87de0395a40d1f1b/alembic/runtime/migration.py#L679-L685

https://github.com/sqlalchemy/alembic/blob/4ff7c6927477c37e2a2ba89b87de0395a40d1f1b/alembic/runtime/migration.py#L700-L706

It would great if this can be supported by PyHive.

**Comment by bkyryliuk** [comment]
We don't run hive3 internally, however we are quite open for the contributions to make it work

**Comment by shawnzhu** [comment]
I've got further inputs from https://groups.google.com/d/msg/sqlalchemy-alembic/t3KmE9KDzH4/ao9u7iRQCgAJ where the expected design in the context of SQLAlchemy is using `supports_sane_rowcount`. see https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=supports_sane_rowcount#sqlalchemy.engine.ResultProxy.rowcount

> `ResultProxy.rowcount` may not be fully implemented by all dialects. In particular, most DBAPIs do not support an aggregate rowcount result from an executemany call. The `ResultProxy.supports_sane_rowcount()` and `ResultProxy.supports_sane_multi_rowcount()` methods will report from the dialect if each usage is known to be supported.

So it just need to simply declare `supports_sane_rowcount = False` in `pyhive.sqlalchemy_hive.HiveDialect`.

**Comment by matsavage** [comment]
Sorry to reopen something so old, but is there a reason that `rowcount` is not supported?

I would really like this feature to measure data flows when using dbt on a spark instance
