### ISSUE TITLE
Pass a job.queue to Hive connection 

### ISSUE THREAD

**Issue by ispmarin** [dropbox/PyHive#33]
I'm connecting to a Hive server that has queues being used. I can do a `show databases` using `pyhive`, but when I try to do a `SELECT` I get the error 

```
TExecuteStatementResp(status=TStatus(errorCode=1, errorMessage='Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask', sqlState='08S01', infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask:29:28'
```

(I'm using Tez on this cluster). I believe that the error is caused by the queue structure. How can I pass a job.queue to the `connect` object?

For example, on `beeline` I have to pass the argument

```
-n hive job.queue.name=myqueue
```
to execute my jobs.

**Comment by jingw** [comment]
For raw DB-API, there's a configuration argument on `connect`:
```
hive.connect('host', configuration={'job.queue.name': 'myqueue'})
```

For sqlalchemy, pass the same thing through connect_args:
```
create_engine(
    'hive://user@host:10000/database',
    connect_args={'configuration': {'job.queue.name': 'myqueue'}}
)
```

**Comment by mshirley** [comment]
Sorry, this is my fault.  I was passing mapreduce.job.queue.name instead of mapred.job.queue.name.
