### ISSUE TITLE
Installation problem:UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42

### ISSUE THREAD

**Issue by AlexLuya** [dropbox/PyHive#34]
Hello,
       My laptop is running Ubuntu 14.04 server 6.4,and python2.7-dev has been installed,when install pyhive,blow errors got printed:
```python
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/sasl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hRzjMT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/sasl
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
````

**Comment by jingw** [comment]
It looks like it's failing to install the `sasl` dependency. Could you try running `pip install sasl`, and if that errors out, bring it up with the `sasl` maintainers?

Also, it looks like the real error message got trumped by an error printing out the error. You'll probably get a more useful message if you edit `/usr/lib/python2.7/dist-packages/pip/basecommand.py` to say ` text = u'\n'.join(complete_log)` (or just print out `complete_log` directly)
