### ISSUE TITLE
pyhive[hive] installation error

### ISSUE THREAD

**Issue by wilberh** [dropbox/PyHive#340]
Python version:  3.6  
Linux environment  

Anyone experience this installation issue?  
After "pip install pyhive[hive]" I get this error -

```
Building wheels for collected packages: sasl
  Building wheel for sasl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /app/username/venv_pyhive/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nzrxvq_x/sasl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nzrxvq_x/sasl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-znem96i8
.
.
.<omitted for breviry>
.
.
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isasl -I/app/username/venv_pyhive/include -I/usr/local/include/python3.6m -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-3.6/sasl/saslwrapper.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  sasl/saslwrapper.cpp:249:10: fatal error: string: No such file or directory
   #include <string>
            ^~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sasl
```

**Comment by OpenDataAlex** [comment]
Do you have the gcc library installed?  You'll also need to install sasl outside of the pip install.

**Comment by wilberh** [comment]
I'm using RHEL6.  

I have sasl:  
cyrus-sasl-devel-2.1.23-15.el6_6.2.x86_64

And gcc library:
libgcc-4.4.7-23.el6.x86_64

**Comment by fgbocci** [comment]
On a Linux system, with python3.7, not 3.6 as you mentioned, was able to fix this by first installing:
```
apt update
apt-get install libsasl2-dev
```

Then I installed pyhive[hive] without any issues. Let me know if it helps you

**Comment by wilberh** [comment]
On RHEL6 or Ubuntu?

**Comment by wilberh** [comment]
Okay; problem fixed.  
Since my environment was setup to use, gcc (GCC) 8.1.0, I then changed it to use, gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23).
So I did this did it -

env CC=/usr/local/bin/gcc-4.9 pip install thrift_sasl==0.2.1

**Comment by wilberh** [comment]
Okay; problem fixed.  
Since my environment was setup to use, gcc (GCC) 8.1.0, I then changed it to use, gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23).
So I did this did it -

env CC=/usr/bin/gcc pip install thrift-sasl
pip install pyhive[hive]
