### ISSUE TITLE
Error doing `SELECT` operations on Hive, `show databases` works fine

### ISSUE THREAD

**Issue by ispmarin** [dropbox/PyHive#35]
I have a Hive server using Tez that I can connect correctly:

    import pyhive
    from pyhive import hive

    cursor = hive.connect(connect_host, port=10000, configuration={'job.queue.name': 'myqueue'}).cursor()
    cursor.execute('use db_20160111') # works fine
    cursor.execute('show databases') # works fine
    cursor.execute('SELECT cgi FROM db_20160111.useful_result') # crashes

with the following error:

    OperationalError: TExecuteStatementResp(status=TStatus(errorCode=1, errorMessage='Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask', sqlState='08S01', infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.tez.TezTask:29:28', 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:314', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:146', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:173', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:256', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:376', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:357', 'sun.reflect.GeneratedMethodAccessor308:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:606', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:79', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:37', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:64', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:415', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1628', 'org.apache.hadoop.hive.shims.HadoopShimsSecure:doAs:HadoopShimsSecure.java:536', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:60', 'com.sun.proxy.$Proxy23:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:234', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:401', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:206', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1145', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:615', 'java.lang.Thread:run:Thread.java:745'], statusCode=3), operationHandle=None)

Thanks!

**Comment by jingw** [comment]
The error is on the Hive server side so it's hard to say what's going on. Are you able to run queries on beeline? In principle beeline also connects to HiveServer2 via Thrift. If beeline works, can you run `set` with both pyhive and beeline and diff the outputs?

**Comment by ispmarin** [comment]
I did some more tests.

1. `set` works both on `beeline` and `pyhive`
2. doing a `select` on a table with name starting with a letter ('mytable') works fine both on pyhive and beeline
2. doing a `select` on a table with the name starting with a number ('2016_mytable') gives me the error, on different tables and different databases. The same query works on beeline

Can I provide anything else to help?

**Comment by jingw** [comment]
Can you try backticking the names? It sounds like the two clients might be
using different Hive configuration. Hive has some config options that
affect identifier handling, e.g. hive.support.quoted.identifiers.

It would be useful to know if `set` returns the same output from both
clients, or if there's some config option that's different.

**Comment by ispmarin** [comment]
I can't backtick the names, but I tested with different tables on the same database and with very similar structure, with the only difference being the names with or without numbers on the beginning of the table names, and got the same results as reported before.

I got the two different `set`s and they're different. For example, the variable `hive.support_quoted_identifies` is getting `u'hive.support.quoted.identifiers=column'` from Pyhive and beeline. Which other variables are important?

Cheers

**Comment by jingw** [comment]
Could you post the full diff of the set outputs? I'm not familiar with Tez so I'm not sure what would be relevant. At this point, I'm pretty sure this is an issue with configuration rather than an issue with the client.

**Comment by ispmarin** [comment]
Unfortunately I can't post the diffs because of company policies. If you could guide me I can try to debug on my side to check what could be going wrong.

**Comment by jingw** [comment]
I can't really help much, sorry. All I can say is to go through every single config and figure out what's different and whether it matters. This is probably a problem with the config that beeline and pyhive are passing up to the thrift server.

**Comment by basebase** [comment]
Do you solved?
I also met
