### ISSUE TITLE
allow user to specify other authMechanism

### ISSUE THREAD

**Issue by twds** [dropbox/PyHive#40]
I want to use the PyHive integrate with SQLAlchemy to operate Hive and Presto.

Presto works well, but for Hive, the authMechanism is fixed,  `PLAIN`.
https://github.com/dropbox/PyHive/search?utf8=%E2%9C%93&q=PLAIN
So when the required mechanism is not `PLAIN`, it will complain:

```
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

Is there way to support authMechanism like pyhs2?
https://github.com/BradRuderman/pyhs2/search?utf8=%E2%9C%93&q=authMechanism&type=Code

**Comment by mistercrunch** [comment]
Read a bit of the code to figure that `NONE` and `NOSASL` are the two only supported options. I needed `NOSASL` and this connection string worked for me:
`hive://localhost:10000/foo_database?auth=NOSASL`

**Comment by jingw** [comment]
NONE/NOSASL are there, #47 tracks kerberos

**Comment by pranavoyo** [comment]
hitting this issue with super 0.26.3 and pyhive 0.6.0 with both PLAIN and NOSASL, please assist
