### ISSUE TITLE
Output Hive `INFO` and  `WARN` messages

### ISSUE THREAD

**Issue by ispmarin** [dropbox/PyHive#41]
When running a query that spawns a `tez` or `mapreduce` job, the `beeline` and `hive` clis provide messages of what Hive is doing. Is there a way to see these messages when a query is done with Pyhive? At least the `application_id` when running under YARN?

**Comment by jingw** [comment]
I don't have support for this. It's probably possible with some upgrade to the Hive Thrift interface version.

**Comment by icaromedeiros** [comment]
Where can we find latest or version-specific (hive 0.14) formal definitions of the Hive Thrift interface?

**Comment by icaromedeiros** [comment]
https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Thrift+API

**Comment by ptallada** [comment]
Hi,

I have implemented this in https://github.com/dropbox/PyHive/pull/48

I hope it can be merged soon :)

**Comment by ptallada** [comment]
Oh, and you can get the application id from one of the first messages :)

**Comment by ispmarin** [comment]
:+1:

**Comment by jingw** [comment]
The README has a sample code snippet for fetching logs now :)
