### ISSUE TITLE
Support modifying session properties

### ISSUE THREAD

**Issue by matthewwardrop** [dropbox/PyHive#42]
Since a while back, Presto has supported session properties (https://github.com/facebook/presto/blob/c5faf6e9027c7e3b21db60962503ff28fc2ce859/presto-main/src/main/java/com/facebook/presto/SystemSessionProperties.java). Is it possible for PyHive to add support for modifying them in a persistent manner? [One can run `set session .... = true`; and it probably changes it, but it does not affect subsequent queries.

**Comment by jingw** [comment]
This is in master now thanks to a pull request.

**Comment by matthewwardrop** [comment]
Thanks @jingw :+1:
