### ISSUE TITLE
Session properties via REST API

### ISSUE THREAD

**Issue by matthewwardrop** [dropbox/PyHive#43]
Is it currently possible to modify session properties via the REST API? If not, would it be possible to add support for it?

**Comment by jingw** [comment]
Sorry, I haven't been able to closely track Presto upstream. If you happen to know where Presto specifies session properties in its HTTP protocol, it's probably not much work to add a dict argument to https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L74 and pass it to https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L160

**Comment by jingw** [comment]
This is in master now thanks to a pull request.

**Comment by matthewwardrop** [comment]
Thanks @jingw . Any chance of a point release, so we can use this more easily downstream?

**Comment by jingw** [comment]
I'll get this out on Monday.

**Comment by jingw** [comment]
Done

**Comment by matthewwardrop** [comment]
Thanks @jingw.
