### ISSUE TITLE
Unsupported mechanism type PLAIN

### ISSUE THREAD

**Issue by wanggaohang** [dropbox/PyHive#47]
when connect to hive (use Kerborse) throws this exception:
thrift.transport.TTransport.TTransportException: Bad status: 3 (Unsupported mechanism type PLAIN)

**Comment by jingw** [comment]
Sorry, Kerberos hasn't been implemented.

**Comment by wanggaohang** [comment]
Thanks, hope this feature will coming soon.

**Comment by MyPythonGitHub** [comment]
Is there any update on this issue ? Has Kerberos been included in pyhive ?

**Comment by jingw** [comment]
Merged a LDAP/KERBEROS diff, though I haven't been able to test Kerberos personally.
