### ISSUE TITLE
can't read Hive NULLs to Decimal

### ISSUE THREAD

**Issue by mschmill** [dropbox/PyHive#49]
There does not seem to be a check for None in HiveDecimal.process_result_value().
If there is a NULL in a Hive column expected as Decimal, it causes TypeError: Cannot convert None to Decimal

Shouldn't this return NaN instead?

**Comment by jingw** [comment]
Good catch, this is as bug. It should probably return NULL/None though, as NaN is technically a non-null floating point value.

**Comment by devinstevenson** [comment]
@mschmill This is now fixed in master branch.
