### ISSUE TITLE
fetchmany argument ignored?

### ISSUE THREAD

**Issue by mschmill** [dropbox/PyHive#51]
I am using PyHive and reading from a table with 527,000 rows, which takes quite a long time to read.
In trying to optimize the process, I found the following timings:

fetchmany(1000) takes 4.2s
fetchmany(2000) takes 8.4s
fetchmany(500) takes 4.2s
fetchmany(500) takes 0.02s if directly preceded by the other fetchmany(500)

It seems like the batch size is 1000 regardless of the argument to fetchmany(). Is this the prescribed behavior? Is there an "under the hood" way to change this to optimize batched reads? Is there a way to "prefetch" so that data can be pipelined?

thanks!

**Comment by jingw** [comment]
Yeah the library hard coded 1000 until a few days ago. In master, Pau Crespi fixed this to use the `arraysize` parameter. However, at least in my experience, this library is CPU bottlenecked in Thrift decoding (hooray Python!), so tuning the fetch size might not help you.

**Comment by jingw** [comment]
As luck would have it, PR #52 will make the Hive portion of this library about an order of magnitude more CPU efficient.
