### ISSUE TITLE
Cannot find a way to create a hive engine with SQLalchemy

### ISSUE THREAD

**Issue by Simobain** [dropbox/PyHive#61]
I'm trying a similar code with the correct uri  and I got the error below. 
```
create_engine(
    'hive://user@host:10000/database',
    connect_args={'configuration': {'hive.exec.reducers.max': '123'}},
)

```
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:hive

**Comment by nik-ffm** [comment]
I had the same problem, because I did not run the `setup.py` first. Did you run this successfully?

**Comment by jingw** [comment]
nik-ffm is right. You need to `pip install` the package to use it.

(SQLAlchemy relies on this: https://github.com/dropbox/PyHive/blob/master/setup.py#L62)
