### ISSUE TITLE
Usage in Caravel

### ISSUE THREAD

**Issue by krlng** [dropbox/PyHive#63]
I use the PyHive Package to connect [Caravel](https://github.com/airbnb/caravel) to Hive. This works well, but for some diagrams the query fails. The problem is, that the alias created in the select is not used for ordering. I am not sure whether this is a PyHive or a Caravel Problem. An example below

Wrong query
`SELECT `source` AS `source`, `target` AS `target`, SUM(value) AS `mysum` 
FROM `sankey` GROUP BY `source`, `target` ORDER BY SUM(value) DESC
LIMIT 50000`

This should have been gerneated
`SELECT `source` AS `source`, `target` AS `target`, SUM(value) AS `mysum` 
FROM `sankey` GROUP BY `source`, `target` ORDER BY `mysum` DESC
LIMIT 50000`

**Comment by jingw** [comment]
The query generation happens in SQLAlchemy. It might be possible to flip some flag or customize the SQL compiler: https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py#L100

**Comment by shkr** [comment]
I receive an error when I connect to hive using pyhive with this sqlalchemy url `hive://hostname:10000/shkr`

`AttributeError: Could not locate column in row for column 'tab_name'`
