### ISSUE TITLE
AttributeError: 'Cursor' object has no attribute 'poll'

### ISSUE THREAD

**Issue by austintrombley** [dropbox/PyHive#64]
For some reason your code breaks on db api example --> 

>>> cursor = hive.connect(host="xx.xxx.xx.xx", port=10000, username="hdfs").cursor()
>>> cursor.execute('SELECT * FROM investor.api LIMIT 10')
>>> 
>>> status = cursor.poll().operationState
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Cursor' object has no attribute 'poll'

**Comment by jingw** [comment]
Could you please upgrade to the latest version?

**Comment by austintrombley** [comment]
Jing,

I did the upgrade and still have the issue:

[root@hdpmaster3 ~]# sudo pip install --upgrade pyhive
Collecting pyhive
  Downloading PyHive-0.2.1.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 2.5MB/s
Requirement already up-to-date: future in /usr/lib/python2.7/site-packages (from pyhive)
Installing collected packages: pyhive
  Found existing installation: PyHive 0.1.8
    Uninstalling PyHive-0.1.8:
      Successfully uninstalled PyHive-0.1.8
  Running setup.py install for pyhive ... done
Successfully installed pyhive-0.2.1
[root@hdpmaster3 ~]#


>>> import pyhive
>>> cursor.execute(sql, async=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: execute() got an unexpected keyword argument 'async'


regards,
Austin D. Trombley, MBA
Senior Manager – Business Intelligence
cell:  415-767-6179
[cid:image001.png@01D1D2C0.16DFE220]<http://www.prosper.com/>

**Comment by jingw** [comment]
Try checking if your PYTHONPATH is correct. I'm quite sure this argument exists in 0.2 onwards :)

```
print pyhive.__version__
print pyhive.__file__
```
and maybe try deleting `pyc` files.

**Comment by austintrombley** [comment]
You are right, I rebooted my system – and it now executes but I never see any of the statuses to see if it is running etc?  it just immediately completes?

>>> cursor.execute(sql, async=True)
>>>
>>> status = cursor.poll().operationState
>>> while status in (TOperationState.INITIALIZED_STATE, TOperationState.RUNNING_STATE):
...     logs = cursor.fetch_logs()
...     for message in logs:
...         print message
...     status = cursor.poll().operationState
...     print status
...
>>>

regards,
Austin D. Trombley, MBA
Senior Manager – Business Intelligence
cell:  415-767-6179
[cid:image001.png@01D1D2C2.7BC59610]<http://www.prosper.com/>

**Comment by jingw** [comment]
I believe Hive only generates logs for non-trivial jobs that trigger a mapreduce. If you run something that triggers the fetch task optimization (e.g. `select f(columns) from table where {some partition col}`) then I think it doesn't log anything.
