### ISSUE TITLE
TypeError: execute() got an unexpected keyword argument 'async'

### ISSUE THREAD

**Issue by austintrombley** [dropbox/PyHive#65]
Getting this error when I test your code

>>> cursor = hive.connect(host="xx.xx.xx", port=10000, username="hdfs").cursor()
>>> cursor.execute('SELECT * FROM investor.api LIMIT 10', async=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: execute() got an unexpected keyword argument 'async'

**Comment by jingw** [comment]
Could you please upgrade to the latest version?
