### ISSUE TITLE
Typo in line 299, where row.tab_name is referenced to fetch table_name

### ISSUE THREAD

**Issue by shkr** [dropbox/PyHive#67]
When connecting to hive with sql_alchemy an AttributeError is thrown. This `Could not locate column in row for column 'tab_name'`. I discovered this issue by registering pyhive with sql_alchemy. Then using a sql_alchemy url `hive://hostname:10000/database_name` to connect to my hive database in airbnb/caravel and then testing the connection.

**Comment by jingw** [comment]
896fa9549ecbf5b270974f53eaf2684c4e30002e, thanks!
