### ISSUE TITLE
Allow inputting passwords to hive connection

### ISSUE THREAD

**Issue by dighjd12** [dropbox/PyHive#75]
Hello all! 

I was wondering why there is no fields or parameters to put in the passwords when we are connecting to hive server? I think it's something that pyhive could easily support.. Maybe I missed it but I could not figure out :p

If there is a workaround, please tell me how. Otherwise, I can work on adding that feature.

**Comment by jingw** [comment]
I don't have my HiveServer2 set up with a password, so it was never useful to me (and I don't have an easy means of testing such features). You might be interested in PR #70.

**Comment by dighjd12** [comment]
@jingw ahh okay. I guess someone's already on it! I'll close this issue then.
