### ISSUE TITLE
Track presto / hive query progress

### ISSUE THREAD

**Issue by bkyryliuk** [dropbox/PyHive#76]
I am wondering if there is a way to track the query progress within pyhive ?

I have found that the library polls the stats on the regular basis:
https://github.com/dropbox/PyHive/blob/b34bdbf51378b3979eaf5eca9e956f06ddc36ca0/pyhive/presto.py#L87

However I couldn't find a way to retrieve the data to calculate the progress.
Any ideas how can it be implemented ?

For context, I am working on adding the SQL editor to the Caravel and that feature would be great for the users.

**Comment by jingw** [comment]
You should be able to call the poll() method right after the execute method. We actually do this ourselves in our internal dashboarding tool.

For SQLAlchemy you need to get underneath SQLAlchemy's wrapper to the raw pyhive cursor:
```
result_proxy = engine.execute(query)
cursor = result_proxy.cursor
cursor.poll()
```

**Comment by bkyryliuk** [comment]
Thank you @jingw  !
