### ISSUE TITLE
setup.py install_dependencies missing dependencies from dev_dependencies

### ISSUE THREAD

**Issue by CalebFenton** [dropbox/PyHive#77]
First, thanks for making this. It's appreciated. I think it'll help me out a lot.

After running `pip install pyhive` I got errors about missing thrift module. I had to install everything in dev_dependencies.txt before the example code would work, e.g.:

```
requests>=1.0.0
sasl>=0.1.3
sqlalchemy>=0.5.8
thrift>=0.8.0
thrift_sasl>=0.1.0
```

I'm thinking these should be part of setup.py's install_dependencies, but it seems like maybe I could possibly be doing something wrong. I can submit a PR with the fix if you indeed agree and don't want to do it yourself.

**Comment by jingw** [comment]
Hello,

They're actually optional dependencies so you can use half of the library. The install instructions are here:
https://github.com/dropbox/PyHive#requirements
