### ISSUE TITLE
Better to be compatible with older version of python-hive interface

### ISSUE THREAD

**Issue by changzong** [dropbox/PyHive#84]
Hi there, my team recently encountered a problem while updrading from hiveserver1 to hiveserver2, which is all methods in our Python code have to be changed from older version style(from ThriftHive) to the new PyHive style, such as from fetchAll to fetchall, from fetchN to fetchmany, etc. Also, when executing a query which doesn't return any results(like INSERT), the new PyHive will raise an error while the older interface will return an empty list. 

So I just think it would be better if PyHive could provide the same coding ways to be compatible with older ThriftHive code, so that programmers can easily migrate their work to PyHive.

Thanks.

**Comment by jingw** [comment]
Thanks for the suggestion. The method names are from the DB-API standard (https://www.python.org/dev/peps/pep-0249/). I'd prefer to avoid adding redundant non-standard methods, as this violates the principle of having exactly one correct way to do something.

If you don't want to find/replace your code, I suggest creating a shim or perhaps monkey patching. (e.g. `class MyCompatibilityLayer(pyhive.Cursor)` or `pyhive.Cursor.fetchAll = pyhive.Cursor.fetchall`)
