### ISSUE TITLE
Timezone Problem 

### ISSUE THREAD

**Issue by jiangxiluning** [dropbox/PyHive#87]
Senario:
1.add '-Duser.timezone=Asia/Shanghai' to HiveServer2  JVM  startup option to make `current_timestamp()` return correct time.
2. HiverServer2 is deployed in Server A.   PyHive is installed in Server B. A and B are all CST which is China Standard Time. 
3. I have a csv to import into a table `tt` which only has one timestamp column named 't'. 
4. The CSV file have same schema as table `tt` in which China local time are stored in ISO string format.
5. I load csv file into a temp table `tt_temp` first. It has one column `t` which is string. Then insert records into `tt` by`insert into table .. select ...`

After a lot of tries, I have found i must do this conversion `from_utc_timestamp(to_utc_timestamp(tt_temp.create_time, 'Asia/Shanghai'), 'EST')`, then I can get correct time. So my question is why is the `EST`？

**Comment by jingw** [comment]
PyHive just returns whatever the Hive server returns. Unless you have evidence that the Hive CLI / Beeline work, but PyHive doesn't, then this is probably a question better suited for the core Hive project.
