### ISSUE TITLE
python3.4+ support ?

### ISSUE THREAD

**Issue by stonebig** [dropbox/PyHive#9]

**Comment by jingw** [comment]
This is something I'd like to have, but realistically it's not going to be a priority for me at Dropbox.

**Comment by stonebig** [comment]
ok thanks, will look for alternatives

**Comment by wingr** [comment]
Any update on timelines (if any) for supporting Python 3?

**Comment by matthewwardrop** [comment]
I submitted a PR completing the Python 3 support here: #101

**Comment by wingr** [comment]
@matthewwardrop 
Thanks for working on this - I look forward to testing it out once it is merged! 🎉 ✨  
(I took a look at the PR, but am not comfortable enough with the connection stuff to help review 😞 )
