### ISSUE TITLE
Can I use pyhive on top of Kerberos authentication ?

### ISSUE THREAD

**Issue by MyPythonGitHub** [dropbox/PyHive#91]
Hi,
            I am currently unable to use pyhive on top of Kerberos authentication. Is there a possible resolution to this please ?

Cheers

**Comment by alexwoolford** [comment]
@MyPythonGitHub : Last July, [Wu Junxian (Rupert)](https://www.linkedin.com/in/axeisghost/) created a [pull request](https://github.com/dropbox/PyHive/pull/70) request that provides support for Kerberos. It passed all the checks. I'm not sure why it wasn't merged.

I also needed to access Hive, using PyHive, on a Kerberized cluster. My kludgy hack was to copy the code  from Rupert's pull request into `/usr/lib/python2.7/site-packages/pyhive/hive.py`. After I did this, I was able to access Kerberized Hive using SQLAlchemy.

**Comment by evinhas** [comment]
Please, could you provide more details about using Rupert's code? I have just used the same approach, but I am still getting the error "Unsupported mechanism type PLAIN", that it get used to appear when Kerberos is activated but you are using a URL in a not-kerberos way.

Note: I am using a URL similar to the following one (changing "host", "database" and "MY-REALM" for the correct values):
hive://hots:10000/database;AuthMech=1;KrbRealm=MY-REALM;KrbHostFQDN=host;KrbServiceName=hive

**Comment by jingw** [comment]
duplicates #47, I'll get getting to this shortly

**Comment by ExpressGit** [comment]
pyhive access hive on kerberos ,do you provide an demo?@jingw
