### ISSUE TITLE
Error message: Client protocol is unset

### ISSUE THREAD

**Issue by wjdecorte** [dropbox/PyHive#95]
I'm looking for some guidance with an error message that I get when attempting to create a cursor.

The error message is "Required field 'client_protocol' is unset!".

From some research I found, I believe the issue is related to our older version of Hive (0.12). Unfortunately for the moment we are stuck on that version. If this is indeed the reason, is there a version of PyHive that is compatible with the older Hive? If not, could someone please provide direction on how to resolve this error message? 

Thanks in advance for any help.

**Comment by jingw** [comment]
The 0.1.x series should work on Hive 0.11. I haven't personally tested Hive
0.12, but I'd think it would work.
https://github.com/dropbox/PyHive/releases

**Comment by wjdecorte** [comment]
Thanks.  I'll give it a try.
